name: 构建和发布

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'pnpm'
          
      - name: 安装依赖
        run: pnpm install
        
      - name: 构建应用
        run: pnpm run build
          
      - name: 上传构建产物到 Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 