name: 构建和发布

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: 更新PNPM
        run: pnpm update

      - name: 安装依赖
        run: pnpm install

      - name: 构建应用
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run dist

      # - name: 上传构建产物到 Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       dist/*.exe
      #       dist/*.zip
      #       dist/*.yml
      #       dist/*.blockmap